name = "ADburgers"
uuid = "14300435-0f62-4357-96ba-8a8850622222"
version = "0.1.0"
authors = ["Daily <daily@example.com>"]

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = "1.11.0"
julia = "1.10"
